# Preparando o ambiente

In [1]:
# instalações
!pip install -q ultraplot cartopy salem rasterio pyproj geopandas

# importa bibliotecas
import ultraplot as uplt
import cartopy.crs as ccrs
import cartopy.io.shapereader as shpreader
import pandas as pd
from datetime import timedelta, datetime
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import LinearSegmentedColormap
import os
import imageio
import glob
import calendar
import pandas as pd
import glob
import numpy as np
import xarray as xr
import time
import salem
from geopy.distance import geodesic
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

# monta o drive
from google.colab import drive
drive.mount('/content/drive')

# diretório raiz
dir = '/content/drive/MyDrive/2-PESQUISA/artigo_queimadas_vanessa_2025/0_round1_revisoes'

# diretório de entrada
dir_input = f'{dir}/output/01_focos_raw'

# diretório de saída
dir_output = f'{dir}/output'

# cria pasta de saída
os.makedirs(dir_output, exist_ok=True)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 50.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 83.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.1/86.1 kB 6.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.5/83.5 kB 6.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 81.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 78.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 57.7 MB/s eta 0:00:00
Downloading salem-sample-data...
Mounted at /content/drive

# Leitura dos dados da estações de medição de qualidade do ar

In [2]:
# leitura dos dados da estações de medição de qualidade do ar
df_estacoes = pd.read_excel(f'{dir}/input/Informações-estações.xlsx')
df_estacoes.iloc[6,0] = 'Campinas'
df_estacoes.iloc[10,0] = 'Cubatão'
df_estacoes.iloc[16,0] = 'Guarulhos'
df_estacoes.iloc[17,0] = 'Santo André'
#df_estacoes = df_estacoes.drop(14) # São Caetano do Sul não tem dados
df_estacoes.iloc[14,4] = '-99.9'
df_estacoes.iloc[14,5] = '-99.9'

# lista das estações que serão utilizadas
#estacoes_selecionadas = ['São José do Rio Preto', 'Jaú', 'Ribeirão Preto', 'Araçatuba', 'Jundiaí']
estacoes_selecionadas = ['São José do Rio Preto', 'Ribeirão Preto', 'Jaú', 'Jundiaí']

# seleciona estações
df_estacoes_selecionadas = df_estacoes[ df_estacoes['Estação'].isin(estacoes_selecionadas) ]

# mostra a nova tabela
df_estacoes_selecionadas

                 Estação  Código       Lat       Lon PM10 (%) O3 (%)
2  São José do Rio Preto     116 -20.78470 -49.39830    86.85  82.51
3         Ribeirão Preto     288 -21.17708 -47.81900    76.71  69.58
4                    Jaú     110 -22.29862 -48.56746    91.18  84.70
5                Jundiaí     109 -23.19200 -46.89710    92.07  89.68

# Seleciona focos das estações

Enviar os dados diários de focos de calor para os meses de agosto e setembro de 2024, extraídos para as estações de:

- São José do Rio Preto
- Ribeirão Preto
- Jaú
- Jundiaí

In [3]:
#==============================================================================================#
#                          Leitura dos focos de calor de SP em Ago-Set de 2024
#==============================================================================================#
# cria uma tabela
df_2024 = pd.DataFrame()

# arquivo
file = 'focos_br_ref_2024.zip'

# leitura da tabela
df_2024 = pd.read_csv(f'{dir_input}/{file}', compression='zip', usecols=['lat', 'lon', 'data_pas', 'estado', 'municipio'])

# transforma a coluna "datahora" para o formato "datetime"
df_2024['data_pas'] = pd.to_datetime(df_2024['data_pas'])

# seta a coluna "data_pas" como o índice da tabela
df_2024.set_index('data_pas', inplace=True)

# ordena a tabela pelo índice
df_2024.sort_index(inplace=True)

# focos de calor em SP
df_2024_sp = df_2024[ df_2024['estado'] == 'SÃO PAULO' ]

# seleciona ago e set
df_2024_sp_ago_set = df_2024_sp.loc['2024-08': '2024-09']

# remover a coluna "estado"
#df_2024_sp_ago_set.drop(columns=['estado'], inplace=True)

#==============================================================================================#
#                             Distância máxima em km
#==============================================================================================#
dismax = 20.0

#==============================================================================================#
#     Função que calcula a distância entre o focos e a estação de medição de qualidade do ar
#==============================================================================================#
def calcular_focos_proximos(estacao, df_focos, distancia_maxima):

    # Calcula distâncias para todos os focos
    #Exemplo:
    #2024-08-01 17:49:00    296.199143
    #2024-08-01 17:49:00    249.717281
    distancias = df_focos.apply(lambda x: geodesic((estacao['Lat'], estacao['Lon']), (x['lat'], x['lon'])).km, axis=1)

    # Filtra focos dentro do raio.
    #Exemplo:
    #2024-08-01 17:49:00    False
    #2024-08-01 17:49:00    False
    mask = distancias <= distancia_maxima

    focos_proximos = df_focos[mask].copy()

    focos_proximos['distancia_km'] = distancias[mask]

    focos_proximos['Estação_Referencia'] = estacao['Estação']

    #print('==================================', estacao['Estação'], '==================================' )
    #print(distancias, '\n', mask, df_focos)

    return {'Estação': estacao['Estação'],
            'Quantidade': len(focos_proximos),
            'DataFrame': focos_proximos}

#==============================================================================================#
#                              Processa todas as estações
#==============================================================================================#
resultados = [ calcular_focos_proximos(linha, df_2024_sp_ago_set, dismax) for _, linha in df_estacoes_selecionadas.iterrows() ]

#==============================================================================================#
#                             Salva os CSVs e exibe resumo
#==============================================================================================#
for resultado in resultados:

    nome_sanitizado = 'focos_por_estacao_' + resultado['Estação'].replace("/", "-").replace("\\", "-")

    nome_arquivo = f'{dir_output}/{nome_sanitizado}_{int(dismax)}km.csv'

    resultado['DataFrame'].to_csv(nome_arquivo, index=True)

    print(f"Salvo {nome_arquivo} - {resultado['Quantidade']} focos encontrados")

print("Processo concluído!")

Salvo /content/drive/MyDrive/2-PESQUISA/artigo_queimadas_vanessa_2025/0_round1_revisoes/output/focos_por_estacao_São José do Rio Preto_20km.csv - 79 focos encontrados
Salvo /content/drive/MyDrive/2-PESQUISA/artigo_queimadas_vanessa_2025/0_round1_revisoes/output/focos_por_estacao_Ribeirão Preto_20km.csv - 83 focos encontrados
Salvo /content/drive/MyDrive/2-PESQUISA/artigo_queimadas_vanessa_2025/0_round1_revisoes/output/focos_por_estacao_Jaú_20km.csv - 71 focos encontrados
Salvo /content/drive/MyDrive/2-PESQUISA/artigo_queimadas_vanessa_2025/0_round1_revisoes/output/focos_por_estacao_Jundiaí_20km.csv - 41 focos encontrados
Processo concluído!

In [4]:
# mostra os focos de sp em ago-set de 2024
df_2024_sp_ago_set

                          lat       lon     estado                municipio
data_pas
2024-08-01 17:49:00 -21.68418 -48.85470  SÃO PAULO                 IBITINGA
2024-08-01 17:49:00 -21.68582 -48.86524  SÃO PAULO                 IBITINGA
2024-08-01 17:49:00 -23.36720 -49.23908  SÃO PAULO                   TEJUPÁ
2024-08-01 17:49:00 -22.89354 -49.61684  SÃO PAULO  SANTA CRUZ DO RIO PARDO
2024-08-01 17:49:00 -21.64608 -49.75835  SÃO PAULO                     LINS
...                       ...       ...        ...                      ...
2024-09-30 17:20:00 -20.18561 -50.00773  SÃO PAULO                  CARDOSO
2024-09-30 17:20:00 -20.15956 -50.03808  SÃO PAULO             PEDRANÓPOLIS
2024-09-30 17:20:00 -20.18839 -50.03463  SÃO PAULO             PEDRANÓPOLIS
2024-09-30 17:20:00 -20.19122 -50.02717  SÃO PAULO                   PARISI
2024-09-30 17:20:00 -20.17396 -50.03622  SÃO PAULO             PEDRANÓPOLIS

[6134 rows x 4 columns]

In [5]:
# mostra os dados
resultados

[{'Estação': 'São José do Rio Preto',
  'Quantidade': 79,
  'DataFrame':                           lat       lon     estado              municipio  \
  data_pas
  2024-08-03 17:34:00 -20.75981 -49.25706  SÃO PAULO               GUAPIAÇU
  2024-08-03 17:34:00 -20.76125 -49.26792  SÃO PAULO               GUAPIAÇU
  2024-08-03 17:34:00 -20.76930 -49.25560  SÃO PAULO               GUAPIAÇU
  2024-08-03 17:34:00 -20.77074 -49.26646  SÃO PAULO               GUAPIAÇU
  2024-08-04 18:13:00 -20.70638 -49.36021  SÃO PAULO                 IPIGUÁ
  ...                       ...       ...        ...                    ...
  2024-09-26 17:54:00 -20.83603 -49.51353  SÃO PAULO               MIRASSOL
  2024-09-26 17:54:00 -20.80007 -49.27740  SÃO PAULO  SÃO JOSÉ DO RIO PRETO
  2024-09-26 17:54:00 -20.80158 -49.28726  SÃO PAULO  SÃO JOSÉ DO RIO PRETO
  2024-09-26 17:54:00 -20.80914 -49.27578  SÃO PAULO  SÃO JOSÉ DO RIO PRETO
  2024-09-26 17:54:00 -20.87141 -49.56084  SÃO PAULO                   JACI

                       distancia_km     Estação_Referencia
  data_pas
  2024-08-03 17:34:00     14.962880  São José do Rio Preto
  2024-08-03 17:34:00     13.822072  São José do Rio Preto
  2024-08-03 17:34:00     14.956004  São José do Rio Preto
  2024-08-03 17:34:00     13.814381  São José do Rio Preto
  2024-08-04 18:13:00      9.535424  São José do Rio Preto
  ...                           ...                    ...
  2024-09-26 17:54:00     13.273661  São José do Rio Preto
  2024-09-26 17:54:00     12.701825  São José do Rio Preto
  2024-09-26 17:54:00     11.710787  São José do Rio Preto
  2024-09-26 17:54:00     13.039444  São José do Rio Preto
  2024-09-26 17:54:00     19.452542  São José do Rio Preto

  [79 rows x 6 columns]},
 {'Estação': 'Ribeirão Preto',
  'Quantidade': 83,
  'DataFrame':                           lat       lon     estado       municipio  \
  data_pas
  2024-08-05 17:17:00 -21.01192 -47.87478  SÃO PAULO     SERTÃOZINHO
  2024-08-05 17:17:00 -21.00992 -47.85788  SÃO PAULO    JARDINÓPOLIS
  2024-08-05 17:17:00 -21.00796 -47.84134  SÃO PAULO    JARDINÓPOLIS
  2024-08-05 17:17:00 -21.00784 -47.87003  SÃO PAULO    JARDINÓPOLIS
  2024-08-05 17:17:00 -21.00597 -47.85317  SÃO PAULO    JARDINÓPOLIS
  ...                       ...       ...        ...             ...
  2024-09-03 17:11:00 -21.16297 -47.74541  SÃO PAULO  RIBEIRÃO PRETO
  2024-09-03 17:11:00 -21.16057 -47.72247  SÃO PAULO  RIBEIRÃO PRETO
  2024-09-04 17:52:00 -21.25541 -47.86970  SÃO PAULO  RIBEIRÃO PRETO
  2024-09-06 17:34:00 -21.10045 -47.81461  SÃO PAULO  RIBEIRÃO PRETO
  2024-09-23 17:32:00 -21.29151 -47.67834  SÃO PAULO       CRAVINHOS

                       distancia_km Estação_Referencia
  data_pas
  2024-08-05 17:17:00     19.182740     Ribeirão Preto
  2024-08-05 17:17:00     18.943439     Ribeirão Preto
  2024-08-05 17:17:00     18.868000     Ribeirão Preto
  2024-08-05 17:17:00     19.473716     Ribeirão Preto
  2024-08-05 17:17:00     19.274824     Ribeirão Preto
  ...                           ...                ...
  2024-09-03 17:11:00      7.800524     Ribeirão Preto
  2024-09-03 17:11:00     10.190230     Ribeirão Preto
  2024-09-04 17:52:00     10.145033     Ribeirão Preto
  2024-09-06 17:34:00      8.496630     Ribeirão Preto
  2024-09-23 17:32:00     19.331992     Ribeirão Preto

  [83 rows x 6 columns]},
 {'Estação': 'Jaú',
  'Quantidade': 71,
  'DataFrame':                           lat       lon     estado    municipio  distancia_km  \
  data_pas
  2024-08-03 17:34:00 -22.31179 -48.49586  SÃO PAULO          JAÚ      7.520405
  2024-08-03 17:34:00 -22.31320 -48.50643  SÃO PAULO          JAÚ      6.492431
  2024-08-03 17:34:00 -22.32109 -48.49432  SÃO PAULO          JAÚ      7.936221
  2024-08-03 17:34:00 -22.32252 -48.50501  SÃO PAULO          JAÚ      6.957596
  2024-08-03 17:34:00 -22.33041 -48.49294  SÃO PAULO          JAÚ      8.446539
  ...                       ...       ...        ...          ...           ...
  2024-09-26 17:54:00 -22.23611 -48.65430  SÃO PAULO       ITAPUÍ     11.314726
  2024-09-28 17:34:00 -22.29158 -48.65259  SÃO PAULO          JAÚ      8.806974
  2024-09-28 17:34:00 -22.38485 -48.73752  SÃO PAULO  PEDERNEIRAS     19.951705
  2024-09-28 17:34:00 -22.29010 -48.64107  SÃO PAULO          JAÚ      7.643788
  2024-09-28 17:34:00 -22.37305 -48.64540  SÃO PAULO          JAÚ     11.506430

                      Estação_Referencia
  data_pas
  2024-08-03 17:34:00                Jaú
  2024-08-03 17:34:00                Jaú
  2024-08-03 17:34:00                Jaú
  2024-08-03 17:34:00                Jaú
  2024-08-03 17:34:00                Jaú
  ...                                ...
  2024-09-26 17:54:00                Jaú
  2024-09-28 17:34:00                Jaú
  2024-09-28 17:34:00                Jaú
  2024-09-28 17:34:00                Jaú
  2024-09-28 17:34:00                Jaú

  [71 rows x 6 columns]},
 {'Estação': 'Jundiaí',
  'Quantidade': 41,
  'DataFrame':                           lat       lon     estado             municipio  \
  data_pas
  2024-08-06 17:56:00 -23.24764 -46.74671  SÃO PAULO  CAMPO LIMPO PAULISTA
  2024-08-07 16:58:00 -23.30738 -46.92079  SÃO PAULO               JUNDIAÍ
  2024-08-08 17:39:00 -23.05400 -46.96201  SÃO PAULO               VINHEDO
  2024-08-08 17:39:00 -23.24072 -46.79568  SÃO PAULO  CAMPO LIMPO PAULISTA
  2024-08-08 17:39:00 -23.23924 -46.78589  SÃO PAULO  CAMPO LIMPO PAULISTA
  2024-08-08 17:39:00 -23.25253 -46.87397  SÃO PAULO               JUNDIAÍ
  2024-08-20 17:34:00 -23.13377 -46.89245  SÃO PAULO               JUNDIAÍ
  2024-08-20 17:34:00 -23.14133 -46.88126  SÃO PAULO               JUNDIAÍ
  2024-08-21 18:13:00 -23.17884 -46.77333  SÃO PAULO  CAMPO LIMPO PAULISTA
  2024-08-21 18:13:00 -23.18567 -46.80542  SÃO PAULO               JUNDIAÍ
  2024-08-21 18:13:00 -23.19111 -46.80830  SÃO PAULO       VÁRZEA PAULISTA
  2024-08-21 18:13:00 -23.18455 -46.77634  SÃO PAULO  CAMPO LIMPO PAULISTA
  2024-08-23 17:56:00 -23.12218 -46.99089  SÃO PAULO               JUNDIAÍ
  2024-08-23 17:56:00 -23.10013 -46.99548  SÃO PAULO              LOUVEIRA
  2024-08-23 17:56:00 -23.09935 -47.00236  SÃO PAULO               VINHEDO
  2024-08-23 17:56:00 -23.25132 -46.87104  SÃO PAULO               JUNDIAÍ
  2024-08-23 17:56:00 -23.37215 -46.90429  SÃO PAULO               CAJAMAR
  2024-08-23 17:56:00 -23.36933 -46.88876  SÃO PAULO               CAJAMAR
  2024-08-23 17:56:00 -23.28743 -46.87992  SÃO PAULO               JUNDIAÍ
  2024-08-23 17:56:00 -23.28463 -46.86441  SÃO PAULO               CAJAMAR
  2024-08-23 17:56:00 -23.26241 -46.86877  SÃO PAULO               JUNDIAÍ
  2024-08-23 17:56:00 -23.25949 -46.86018  SÃO PAULO               JUNDIAÍ
  2024-08-23 17:56:00 -23.33171 -46.87061  SÃO PAULO               CAJAMAR
  2024-09-01 17:28:00 -23.18857 -47.03431  SÃO PAULO               ITUPEVA
  2024-09-01 17:28:00 -23.19003 -47.04552  SÃO PAULO               ITUPEVA
  2024-09-01 17:28:00 -23.19149 -47.05679  SÃO PAULO               ITUPEVA
  2024-09-01 17:28:00 -23.19957 -47.04398  SÃO PAULO               ITUPEVA
  2024-09-01 17:28:00 -23.19813 -47.03286  SÃO PAULO               ITUPEVA
  2024-09-02 18:09:00 -23.18303 -46.71165  SÃO PAULO                JARINU
  2024-09-03 17:09:00 -23.28620 -46.83434  SÃO PAULO       FRANCO DA ROCHA
  2024-09-03 17:09:00 -23.27340 -46.83615  SÃO PAULO               JUNDIAÍ
  2024-09-04 17:52:00 -23.33887 -46.92664  SÃO PAULO               CAJAMAR
  2024-09-04 17:52:00 -23.33694 -46.91509  SÃO PAULO               CAJAMAR
  2024-09-04 17:52:00 -23.09166 -46.73911  SÃO PAULO                JARINU
  2024-09-11 17:39:00 -23.24185 -46.79317  SÃO PAULO  CAMPO LIMPO PAULISTA
  2024-09-12 18:19:00 -23.25964 -46.81973  SÃO PAULO               JUNDIAÍ
  2024-09-13 17:22:00 -23.34763 -46.90835  SÃO PAULO               CAJAMAR
  2024-09-13 17:22:00 -23.34533 -46.91442  SÃO PAULO               CAJAMAR
  2024-09-13 17:22:00 -23.34356 -46.89987  SÃO PAULO               CAJAMAR
  2024-09-13 17:22:00 -23.26872 -46.82253  SÃO PAULO               JUNDIAÍ
  2024-09-28 17:34:00 -23.08469 -47.01731  SÃO PAULO               VINHEDO

                       distancia_km Estação_Referencia
  data_pas
  2024-08-06 17:56:00     16.580802            Jundiaí
  2024-08-07 16:58:00     13.005983            Jundiaí
  2024-08-08 17:39:00     16.666507            Jundiaí
  2024-08-08 17:39:00     11.699638            Jundiaí
  2024-08-08 17:39:00     12.528009            Jundiaí
  2024-08-08 17:39:00      7.109292            Jundiaí
  2024-08-20 17:34:00      6.466312            Jundiaí
  2024-08-20 17:34:00      5.841221            Jundiaí
  2024-08-21 18:13:00     12.755352            Jundiaí
  2024-08-21 18:13:00      9.412283            Jundiaí
  2024-08-21 18:13:00      9.091638            Jundiaí
  2024-08-21 18:13:00     12.390883            Jundiaí
  2024-08-23 17:56:00     12.330184            Jundiaí
  2024-08-23 17:56:00     14.318744            Jundiaí
  2024-08-23 17:56:00     14.882429            Jundiaí
  2024-08-23 17:56:00      7.090371            Jundiaí
  2024-08-23 17:56:00     19.964803            Jundiaí
  2024-08-23 17:56:00     19.657461            Jundiaí
  2024-08-23 17:56:00     10.713873            Jundiaí
  2024-08-23 17:56:00     10.790277            Jundiaí
  2024-08-23 17:56:00      8.319366            Jundiaí
  2024-08-23 17:56:00      8.375258            Jundiaí
  2024-08-23 17:56:00     15.708189            Jundiaí
  2024-09-01 17:28:00     14.052456            Jundiaí
  2024-09-01 17:28:00     15.196465            Jundiaí
  2024-09-01 17:28:00     16.348704            Jundiaí
  2024-09-01 17:28:00     15.060056            Jundiaí
  2024-09-01 17:28:00     13.914949            Jundiaí
  2024-09-02 18:09:00     19.012409            Jundiaí
  2024-09-03 17:09:00     12.251080            Jundiaí
  2024-09-03 17:09:00     10.962645            Jundiaí
  2024-09-04 17:52:00     16.543972            Jundiaí
  2024-09-04 17:52:00     16.156977            Jundiaí
  2024-09-04 17:52:00     19.628873            Jundiaí
  2024-09-11 17:39:00     11.985282            Jundiaí
  2024-09-12 18:19:00     10.900611            Jundiaí
  2024-09-13 17:22:00     17.274074            Jundiaí
  2024-09-13 17:22:00     17.073179            Jundiaí
  2024-09-13 17:22:00     16.787325            Jundiaí
  2024-09-13 17:22:00     11.421011            Jundiaí
  2024-09-28 17:34:00     17.111672            Jundiaí  }]

In [6]:
df = pd.read_csv(nome_arquivo)
df

,data_pas,lat,lon,estado,municipio,distancia_km,Estação_Referencia
0,2024-08-06 17:56:00,-23.24764,-46.74671,SÃO PAULO,CAMPO LIMPO PAULISTA,16.580802,Jundiaí
1,2024-08-07 16:58:00,-23.30738,-46.92079,SÃO PAULO,JUNDIAÍ,13.005983,Jundiaí
2,2024-08-08 17:39:00,-23.05400,-46.96201,SÃO PAULO,VINHEDO,16.666507,Jundiaí
3,2024-08-08 17:39:00,-23.24072,-46.79568,SÃO PAULO,CAMPO LIMPO PAULISTA,11.699638,Jundiaí
4,2024-08-08 17:39:00,-23.23924,-46.78589,SÃO PAULO,CAMPO LIMPO PAULISTA,12.528009,Jundiaí
5,2024-08-08 17:39:00,-23.25253,-46.87397,SÃO PAULO,JUNDIAÍ,7.109292,Jundiaí
6,2024-08-20 17:34:00,-23.13377,-46.89245,SÃO PAULO,JUNDIAÍ,6.466312,Jundiaí
7,2024-08-20 17:34:00,-23.14133,-46.88126,SÃO PAULO,JUNDIAÍ,5.841221,Jundiaí
8,2024-08-21 18:13:00,-23.17884,-46.77333,SÃO PAULO,CAMPO LIMPO PAULISTA,12.755352,Jundiaí
9,2024-08-21 18:13:00,-23.18567,-46.80542,SÃO PAULO,JUNDIAÍ,9.412283,Jundiaí
10,2024-08-21 18:13:00,-23.19111,-46.80830,SÃO PAULO,VÁRZEA PAULISTA,9.091638,Jundiaí
11,2024-08-21 18:13:00,-23.18455,-46.77634,SÃO PAULO,CAMPO LIMPO PAULISTA,12.390883,Jundiaí
12,2024-08-23 17:56:00,-23.12218,-46.99089,SÃO PAULO,JUNDIAÍ,12.330184,Jundiaí
13,2024-08-23 17:56:00,-23.10013,-46.99548,SÃO PAULO,LOUVEIRA,14.318744,Jundiaí
14,2024-08-23 17:56:00,-23.09935,-47.00236,SÃO PAULO,VINHEDO,14.882429,Jundiaí
15,2024-08-23 17:56:00,-23.25132,-46.87104,SÃO PAULO,JUNDIAÍ,7.090371,Jundiaí
16,2024-08-23 17:56:00,-23.37215,-46.90429,SÃO PAULO,CAJAMAR,19.964803,Jundiaí
17,2024-08-23 17:56:00,-23.36933,-46.88876,SÃO PAULO,CAJAMAR,19.657461,Jundiaí
18,2024-08-23 17:56:00,-23.28743,-46.87992,SÃO PAULO,JUNDIAÍ,10.713873,Jundiaí
19,2024-08-23 17:56:00,-23.28463,-46.86441,SÃO PAULO,CAJAMAR,10.790277,Jundiaí
20,2024-08-23 17:56:00,-23.26241,-46.86877,SÃO PAULO,JUNDIAÍ,8.319366,Jundiaí
21,2024-08-23 17:56:00,-23.25949,-46.86018,SÃO PAULO,JUNDIAÍ,8.375258,Jundiaí
22,2024-08-23 17:56:00,-23.33171,-46.87061,SÃO PAULO,CAJAMAR,15.708189,Jundiaí
23,2024-09-01 17:28:00,-23.18857,-47.03431,SÃO PAULO,ITUPEVA,14.052456,Jundiaí
24,2024-09-01 17:28:00,-23.19003,-47.04552,SÃO PAULO,ITUPEVA,15.196465,Jundiaí
25,2024-09-01 17:28:00,-23.19149,-47.05679,SÃO PAULO,ITUPEVA,16.348704,Jundiaí
26,2024-09-01 17:28:00,-23.19957,-47.04398,SÃO PAULO,ITUPEVA,15.060056,Jundiaí
27,2024-09-01 17:28:00,-23.19813,-47.03286,SÃO PAULO,ITUPEVA,13.914949,Jundiaí
28,2024-09-02 18:09:00,-23.18303,-46.71165,SÃO PAULO,JARINU,19.012409,Jundiaí
29,2024-09-03 17:09:00,-23.28620,-46.83434,SÃO PAULO,FRANCO DA ROCHA,12.251080,Jundiaí
30,2024-09-03 17:09:00,-23.27340,-46.83615,SÃO PAULO,JUNDIAÍ,10.962645,Jundiaí
31,2024-09-04 17:52:00,-23.33887,-46.92664,SÃO PAULO,CAJAMAR,16.543972,Jundiaí
32,2024-09-04 17:52:00,-23.33694,-46.91509,SÃO PAULO,CAJAMAR,16.156977,Jundiaí
33,2024-09-04 17:52:00,-23.09166,-46.73911,SÃO PAULO,JARINU,19.628873,Jundiaí
34,2024-09-11 17:39:00,-23.24185,-46.79317,SÃO PAULO,CAMPO LIMPO PAULISTA,11.985282,Jundiaí
35,2024-09-12 18:19:00,-23.25964,-46.81973,SÃO PAULO,JUNDIAÍ,10.900611,Jundiaí
36,2024-09-13 17:22:00,-23.34763,-46.90835,SÃO PAULO,CAJAMAR,17.274074,Jundiaí
37,2024-09-13 17:22:00,-23.34533,-46.91442,SÃO PAULO,CAJAMAR,17.073179,Jundiaí
38,2024-09-13 17:22:00,-23.34356,-46.89987,SÃO PAULO,CAJAMAR,16.787325,Jundiaí
39,2024-09-13 17:22:00,-23.26872,-46.82253,SÃO PAULO,JUNDIAÍ,11.421011,Jundiaí
40,2024-09-28 17:34:00,-23.08469,-47.01731,SÃO PAULO,VINHEDO,17.111672,Jundiaí